### ISSUE TITLE
Schedule validator

### ISSUE THREAD

**Issue by dtopaloglou** [SOEN341-W16/ConUScheduler#117]
Validate user's chosen schedule.

**Comment by dtopaloglou** [comment]
@MarcLeclair if you do any commits, please reference this issue's number in your comments.

**Comment by dtopaloglou** [comment]
@MarcLeclair to append to an HTML tag, use `$('#ajax-result').html('foo')`; Also, if you wish to call `actionScheduleValidation`, you need to reference it as `'schedule/ScheduleValidation'`. Include the code on your next commit.

**Comment by Malclir** [comment]
@dtopaloglou  alright, thought i included it. deleted half my code. Goanna have to re do it all. BRB....

Also, was using that with 'data' yet nothing showed up :/

**Comment by dtopaloglou** [comment]
@MarcLeclair did you manage to fix this?

**Comment by Malclir** [comment]
Well the code is back however I haven't been able to display anything on
the div. It just doesn't want to. I've tried to destroy the dialog doesn't
work. Tried to echo doesn't work tried to encode in Json still doesn't do
much.

**Comment by dtopaloglou** [comment]
@MarcLeclair You'll have to show me on Friday because I'm not sure where the problem is in your code. First off, I don't even see a `div`called `ajax-results` so you won't see anything come up.

**Comment by Malclir** [comment]
It's there in my code! At least in php storm.  I'll show you tomorrow in
331?

**Comment by dtopaloglou** [comment]
Yes! Right before class or something.
