### ISSUE TITLE
Introduction to System

### ISSUE THREAD

**Issue by claudds** [SOEN341-W16/ConUScheduler#12]
As a starter, the intro should simply introduce the reasons behind our creation of this model (try looking at intros from previous projects to get an idea), give a simple outline of the system and trace a step by step general use case or a few general use cases for different users. 

This should or could be up to a page long; you can take your ideas from the System Description from Deliverable 0.

**Comment by dtopaloglou** [comment]
Should this be an issue within a Milestone? Say Deliverable 1?

**Comment by claudds** [comment]
Agh, it was supposed to be, i'll redo it!

**Comment by dtopaloglou** [comment]
Don't delete it.

**Comment by claudds** [comment]
figured it out!

**Comment by dtopaloglou** [comment]
Good!

**Comment by claudds** [comment]
@RyanL94

**Comment by claudds** [comment]
@RyanL94 Could you please have this done by Wednesday evening, before our next team meeting please? :)
