### ISSUE TITLE
Deliverable 3 - 3.2.3 Stress Testing 

### ISSUE THREAD

**Issue by claudds** [SOEN341-W16/ConUScheduler#126]
NOTE: refer to team cobalt's past project, this section may or may not include test code (would be an extra)

Describe potential extreme situations of system usage. Describe the design of tests that would verify system performance under these extreme conditions. Perform the tests and show the results.

**Comment by claudds** [comment]
@dtopaloglou please assign this to one or a few of your team members & follow up with them :)

**Comment by dtopaloglou** [comment]
@erinb90 would you like to do this?
