### ISSUE TITLE
Deliverable 3 - 3.2.4 Security testing 

### ISSUE THREAD

**Issue by claudds** [SOEN341-W16/ConUScheduler#127]
NOTE: from what I reviewed, Cobalt did not have this part in their testing, check STAR's past project for this one

Your project should be tested for security, Including resistance to SQL injection attacks, against at least two automated tools (e.g Nikko and Skipfish).

**Comment by claudds** [comment]
@dtopaloglou maybe you and another coding team member could take this issue?

**Comment by dtopaloglou** [comment]
@erinb90  this could be the other one.
