### ISSUE TITLE
Deliverable 1 - Sections 4.2 and 6.2

### ISSUE THREAD

**Issue by claudds** [SOEN341-W16/ConUScheduler#13]
These are the parts we'll need your guys' input from, given that it highly concerns the software requirements and resources that we want to use and are available to us! @dtopaloglou  will split up the parts and assign them to you all so we don't have too many things to work on!

For sanity purposes, and so that everyone can work on their own parts on their own times, please push your parts in separate files with clear titles (the deliverable name and the section you're writing) so that I'll know which order to add them into the final document!
- [x] **4.2** Technical Resources
- [x] **6.2** Technologies in use

**Comment by dtopaloglou** [comment]
Shouldn't this issue be renamed to Deliverable 1?

**Comment by dtopaloglou** [comment]
@lori-dalkin Did you want to do section 4.1 (Human Resources)?

**Comment by lori-dalkin** [comment]
I can. Where can I find further information on what 4.2 requires?

**Comment by dtopaloglou** [comment]
@lori-dalkin I already did 4.2 and 6.2 (see pull request just above).

**Comment by lori-dalkin** [comment]
Sorry I meant 4.1.

**Comment by dtopaloglou** [comment]
@lori-dalkin Check the Documentation branch -> Deliverable 1. There is a document in there with everything we need for Deliverable 1. 4.1 is the Human Resources: everyone's expertise, skills, etc.

**Comment by lori-dalkin** [comment]
Okay! Will look into it as soon as possible.

**Comment by dtopaloglou** [comment]
@lori-dalkin Awesome. Look at the past projects to see how and what is needed. :smile:

**Comment by dtopaloglou** [comment]
@claudds Once you pull my request, check off the checkboxes (If the pull is good, obviously).

**Comment by swy351** [comment]
I would split each of the tasks (3.1, 3.3. etc. into different issues).
Or even split each of the tasks into small tasks into different issues and assign different people to work on it, instead of having one issue for the entire deliverable.

**Comment by dtopaloglou** [comment]
@swy351 Noted!

Would you also recommend to have each member as a collaborator in this case? We kept only team leaders as collaborators in order to have full control over pull requests. However, this would mean that every team member would need to fork this repo rather than being able to push in it directly.

**Comment by swy351** [comment]
@dtopaloglou I think everyone should be here.
It's ok that everyone can pull, but if you want to control the change, what you need is to control how the push is accepted.
BTW, I think everyone can clone, chagne and push eh?

**Comment by dtopaloglou** [comment]
@swy351 I'm not entirely sure. The Forking mechanism clones this repo to the user's repo. If they wish to change anything, they do the changes in their proper repo and the create a pull request on this current repo. If any of the collaborators accept the pull request, a merge can happen. However, as of now, users cannot push or change unless they create a pull request. Perhaps it'd be best to have everyone as collaborators and moderate who closes pull requests.

**Comment by swy351** [comment]
@dtopaloglou I am not sure how did you configure this repo.
Normally there are cerntain people can make approval such that change can be merged back.
Or you can ignore that step, such that everyone can change and push back.
It really depends on how fancy you want to play with it.
On a side node, I noticed that the issue ids are not referenced in commit comments.
I will mention that again in the class next week btw.

**Comment by dtopaloglou** [comment]
@swy351 Okay. I will try to figure out how the management is going to work with the current settings of this repo; there might be some tweaking that needs to be done. Also, there are a few Issue ids that are in fact referenced in a couple of places (some of the few commits I recently made - see the top of this page). However, not everyone is familiar yet with referencing issue ids in the commits; I'll be keeping a note of that.

**Comment by dtopaloglou** [comment]
@swy351 I figured it out. I needed to make this repo into an Organization instead where we can control read/write permissions and changes. The repo link will be updated on the next deliverable as the old link should no longer be valid.

**Comment by claudds** [comment]
@dtopaloglou Just checked the other projects, Use Cases and Use Case Diagrams should go under section 3.1. I think this section should be delegated to multiple team members as it can get huge, maybe everyone in the group would get one or two test cases each?

**Comment by claudds** [comment]
@dtopaloglou this was the issue i used for 4.2! Just so you know where to add Yii into :)

**Comment by dtopaloglou** [comment]
@claudds Check out 6.2 and let me know if I'm missing anything. Disregard 4.2 though.

**Comment by claudds** [comment]
@dtopaloglou perfect! I'm going to close the issue again, good work!
