### ISSUE TITLE
Deliverable 4 - Detailed Designs Edits

### ISSUE THREAD

**Issue by claudds** [SOEN341-W16/ConUScheduler#142]
Minimal edits from deliverable 3!
- [x] **4.1.1** Remove SavedUsers class. Add in functions from SavedUsers class to both Student and Admin classes 
- [x] **4.1.3** Remove Prerequisite class and add its functions into the Course class. Have an association going from Course to itself called 'prerequisite'
- [ ]  Update Administrator class specifications to include new Methods

**Comment by claudds** [comment]
@KevinYasmine your part in this section would need to be edited as well :)

**Comment by AlineTheAlien** [comment]
@claudds yep and is the class diagram edit for the interfaces also referring to this issue?

**Comment by claudds** [comment]
@AlineTheAlien yes! This issue is for the interfaces only, the entire class diagram edit is referred to in issue #141 :)

**Comment by claudds** [comment]
@KevinYasmine please check aline's updated diagrams and update your class explanations accordingly (i.e. add in administrator methods)!
