### ISSUE TITLE
Section 3.2 Domain Model

### ISSUE THREAD

**Issue by claudds** [SOEN341-W16/ConUScheduler#15]
This section is basically an update of the Domain Model in Deliverable 0. We should go along with the changes the professor indicated to us. Also, it should include the descriptions of each DLO (and remove the descriptions of the DLOs to be removed)

Changes to be made:
- Make the diagram more readable (black font, larger font size, more UML like than it is now)
- Remove User and Admin DLOs
- Associations to be added: 
  -  between Student and Schedule (Student generates Schedule)
  -  between Schedule and Sequence (Schedule depends on Sequence)
# Description

<em>This is a diagram consisting of domain level objects and their attributes and associations. Include an explanation of the model commenting on each component and its relationship to the other components.</em>

**Comment by dtopaloglou** [comment]
@AlineTheAlien I assigned this to you since Claudia mentioned it in the description. :smiling_imp:
