### ISSUE TITLE
Deliverable 4 - Use Case Additions and Modifications

### ISSUE THREAD

**Issue by AlineTheAlien** [SOEN341-W16/ConUScheduler#155]
Any changes made to existing use cases or new cases to be added in the final deliverable. Anyone can  work on this issue too if changes were made! 
- [x] Manage Courses (Administrator)
- [x] Create Course (Administrator)
- [x] View Courses (Administrator)
- [x] Add User (Administrator)
- [x] Search Users (Administrator)
- [x] View User (Administrator)
- [x] Update User (Administrator)
- [x] Delete User (Administrator)
- [ ] Browse User (Administrator)

**Comment by claudds** [comment]
@SOEN341-W16/documentation
