### ISSUE TITLE
Section 6.1 Architecture 

### ISSUE THREAD

**Issue by claudds** [SOEN341-W16/ConUScheduler#17]
For this section, we need to explain the high-level system architecture we've decided on including in the project and give valid and concrete reasons as to why we've chosen this architecture. This section basically outlines the entire model design that the project is based on. 
# Description

<em>Explain the high-level system architecture that you plan for the project, giving explanations as to why you chose such an approach, e.g. a design rationale. Include a high-level architecture diagram (e,g, a high-level UML class diagram). For each module presented in the architecture, also give its rationale, as well as list their individual responsibilities.</em>

**Comment by dtopaloglou** [comment]
@ddicorpo You might want to check this out. Maybe the MVC model?

**Comment by ddicorpo** [comment]
@dtopaloglou Ill take care of this

**Comment by dtopaloglou** [comment]
@ddicorpo We're using an MVC architecture provided by the Yii Framework. You might want to look at the documentation related to Yii.
