### ISSUE TITLE
Deliverable 4 - Revise Failed Test Cases 

### ISSUE THREAD

**Issue by claudds** [SOEN341-W16/ConUScheduler#177]
Here's a list of test cases that have failed in previous versions of the system. please retest them for the final deliverable! 
- [x] 6.6. Student clicks 'generate schedule' with a set of time preferences and for given years and clicks 'validate schedule' without choosing any tutorial and lab sections (**the error message that pops up is empty**)
- [x] 8.1 Student requests to view academic record (**when no classes completed for the student, get a divide by 0 error**)
- [ ] 9.3 Student requests to drop a course that is a prerequisite to another course saved in later semesters and confirms the choice (**The course is successfully dropped but the course requiring it as a prerequisite remains in the later schedule**)
- [ ] 11.2 Student chooses to save a schedule in a semester that already has a saved schedule (**This should be a pass, as it's a requirement that we want**)
- [x] 19.2 (Update User) Administrator hits the save button without changing any fields (**the password changes even tho no changes were indicated**)
- [x] 19.19 (Update User) Administrator clicks on the password field but does not change anything, then saves the profile. (**The password changes even though it should not**).

@ddicorpo @AlineTheAlien @Ideawin @limphilip @RyanL94

**Comment by dtopaloglou** [comment]
@claudds 19.2 and 19.9 ; the admin should not be able to change user passwords once created.

**Comment by dtopaloglou** [comment]
@claudds I can remove the password fields in the Manage User section; this would prefer anyone from changing passwords.

**Comment by claudds** [comment]
@dtopaloglou yes, i think that would be a great idea! I think whoever tested it simply tested all the changeable fields they found, and that was one of them. It makes sense that the administrator would not be able to change someone else's password though.

**Comment by dtopaloglou** [comment]
@claudds 11.2 ? Saving multiple schedules?

**Comment by claudds** [comment]
@dtopaloglou saving multiple schedules in the same semester

**Comment by dtopaloglou** [comment]
#180 I'll be deploying the latest dev branch soon. Whatever is checked, has been fixed.

**Comment by dtopaloglou** [comment]
@SOEN341-W16/documentation bug 6.2 should be okay now. Please verify.

**Comment by claudds** [comment]
@dtopaloglou i believe the two remaining bugs were not fixable at this stage right? If so, we could close the issue!
