### ISSUE TITLE
Section 7.5 Schedule

### ISSUE THREAD

**Issue by claudds** [SOEN341-W16/ConUScheduler#21]
This section is an actual schedule and/or timeline of all of the activities we plan on undertaking throughout the course of this project. It should include start dates, due dates, names of activities, actors in the activities, etc. 

This section is actually a huge help to us and would be very useful in keeping us on track for the coming weeks in the project :)
# Description

<em> Diagrams or tables showing target dates for completion of iterations and phases, release points, demos, and other milestones, e.g. a Gantt chart. </em>

**Comment by AlineTheAlien** [comment]
Is a Gantt diagram enough for this section?

**Comment by claudds** [comment]
@AlineTheAlien yes! As long as all the activities are shown and scheduled, but 7.1 has to be done first.

**Comment by claudds** [comment]
@RyanL94 I think you'd be okay with this part! You can always ask Aline for help with the diagrams :)

**Comment by ddicorpo** [comment]
@RyanL94  You can check out this site for a free gant chart creator: http://www.ganttproject.biz/

**Comment by ddicorpo** [comment]
ill post more if i find
