### ISSUE TITLE
Section 7.6 Risk

### ISSUE THREAD

**Issue by claudds** [SOEN341-W16/ConUScheduler#23]
This section requires us to outline the risks associated and presented by this project, and explain why this is a risk to the project. 

I know this might seem a little ambiguous, but if you think about the fact that this is the first real Software Engineering project for most of us, I'm sure we could find a few risks!.
# Description

List and comment all the elements of the project that present a risk. Explain why they represent a risk.

**Comment by dtopaloglou** [comment]
@claudds I'll do this, or at least I'll try to add as many details as I can.

**Comment by claudds** [comment]
@SOEN341-W16/coding @SOEN341-W16/documentation Dimitri has added a version of some risks, but if anyone would like to add anything to this, feel free to do so!
