### ISSUE TITLE
Section 3.1 Functional Requirements

### ISSUE THREAD

**Issue by claudds** [SOEN341-W16/ConUScheduler#24]
This section should describe the requirements we've decided our system should include and define the actions that must take place in the software. Basically, this is where our use cases will be outlined and the use case diagram will be included. 

Note that we should include ALL features that we would want to include in the project, even some of the features we'd later scope out (and have already decided to scope out). This is just to show that we've progressed already with some of the planning. 

Example of functional requirements:
- Login  
- Logout  
- Create course sequence (personalize course sequence by adding/removing courses)
- Browse list of courses (by name)
- View chosen courses (view sequence)
- Generate Schedule for next 4 years (with preferences)
- View saved schedules (all previously saved generated schedules)
- View academic record (completed courses)
- Remove course from generated schedule (generated)
- Add course to generated schedule (generated)
- Save generated schedule
- View generated schedule (weekly calendar view)

Relative importance and difficulty should be provided in here too. This was one of the sections delegated to @SOEN341-W16/coding 
### Description <h3>

_This section should describe the requirements that the software shall have. It should define the fundamental actions that must take place in the software in accepting and processing the inputs and in processing and generating the outputs. 
The overall functional requirements shall be presented graphically as a **use case model**._

_Each individual requirement shall be presented as a use case. Also, each requirement should be rated in terms of difficulty and importance in order to provide useful discrimination factors for the project scoping presented in section 5._

---
### Use Case Model <h3>

![use case model](https://cloud.githubusercontent.com/assets/5993176/12461522/5aa47120-bf87-11e5-861a-58d51a62c467.png)

**Comment by claudds** [comment]
@MarcLeclair @Ideawin @BDSchoeler @lori-dalkin @dtopaloglou @erinb90 I think you guys could split this issue up into smaller parts, seeing as there are multiple use cases (if you look at past projects, there are actually quite a few use cases). This way everyone gets to contribute!

**Comment by dtopaloglou** [comment]
@Ideawin Maybe help out in here?

**Comment by Ideawin** [comment]
Alright! I was just reading it now ;)

**Comment by dtopaloglou** [comment]
@claudds Don't we want also to be able to just to browse courses and view what they're all about?

**Comment by claudds** [comment]
@dtopaloglou sure! Those were just a few requirements we have brainstormed in class, you guys could add as many as you want!

**Comment by dtopaloglou** [comment]
@claudds I think this Issue should be priority since coding team will need to know what to include in functionality.

**Comment by dtopaloglou** [comment]
@SOEN341-W16/coding We definitely need to talk about this in our next meeting.

**Comment by ddicorpo** [comment]
Functional Requirements:
- Login  
- Add classes
- Drop classes
- Swapping classes
  (Add/Drop/Swap to a specific semester not a specific section)
- View Schedule for current semester
- Change Preferences
- Browse Courses
- Manually Manipulate Sequence (scoped out)
- Professor can view class list (scoped out)
- Admin manages a section (scoped out)
- Professor can drop a class (scoped out)
- Generate Schedule for next 4 years
- Sequence shows you where you are
- View schedule for future semesters
- Generate 1 schedule at a time (scoped out)

**Comment by dtopaloglou** [comment]
@ddicorpo what about completed courses?

**Comment by dtopaloglou** [comment]
@claudds @ddicorpo Please review the requirements in the description on top. I think we should start with those.

**Comment by dtopaloglou** [comment]
@claudds @ddicorpo If you both agree, I'll divide and give them to my team.

**Comment by claudds** [comment]
@dtopaloglou Everything seems good to go to me!

**Comment by dtopaloglou** [comment]
@claudds I need Daniel's okay too :smile:
