### ISSUE TITLE
Section 3.3 Constraints and Qualities

### ISSUE THREAD

**Issue by claudds** [SOEN341-W16/ConUScheduler#25]
Here we should be including design constraints, qualities and non functional requirements that we want our system to meet. So, we could include stuff that pertains to usability, readability, ease of use to the user, etc. I think looking at other project examples would help a lot on this part, as it seems a bit  unclear as to what we could include. 

This section was delegated to @SOEN341-W16/coding 
## Description <h3>

_This section describes applicable quality standards and non-functional requirements that the system shall meet, like: performance, usability, reliability, interoperability, scalability, security, etc.
Include any design constraints, external constraints or other dependencies, hardware or platform requirements._

_Constraints and qualities should be described in concrete terms.  Where possible, metrics should be applied._

**Comment by dtopaloglou** [comment]
@claudds I'll attempt this.

**Comment by claudds** [comment]
@dtopaloglou is there anyone else in the coding group that wants to contribute to documentation as well? Marc or Ideawin maybe? They could help you out as well!

**Comment by dtopaloglou** [comment]
@claudds Not sure LOL. This is rather a small part and already have ideas for it. Once I'm done, I'll commit and you can review and see what else we might add.

**Comment by Malclir** [comment]
I can. The parts were assign by @dtopaloglou  no?

**Comment by dtopaloglou** [comment]
@MarcLeclair I'll write some stuff out. I'll commit and you can open up and check out what else to add to it!

**Comment by Ideawin** [comment]
I'd like to contribute to the documentation as well!! Let me know if you guys need me to do something.

**Comment by Malclir** [comment]
I can do 3.3 and pass it on to you for review and you can send it back to me. I'm not 100% sure what to write for this. Stuff like technical constraints (i.e: performance? knowledge of the team?)?

**Comment by dtopaloglou** [comment]
@MarcLeclair I'll do this part as I'm already in the midst of writing it. See perhaps if there are some other portions you can do.

**Comment by dtopaloglou** [comment]
@Ideawin Check out what else is available, check what the issue is all about and if you find you can take it, self-assign yourself or mention it to the person who's been assigned to the issue. You can work together with that person.

**Comment by ddicorpo** [comment]
Non-Functional Requirements:
- Want to support multiple users at a time (crashes per month <= 2) (max 500)
- Monthly Maintenance (Downtime <= 20 mins)
- Crash max  downtime to reboot <= 35 mins
- General Response time <= 100 nano seconds
- Schedule generation response time (between 2-5 seconds)
- User manual has to be provided (either written or video)

**Comment by ddicorpo** [comment]
@dtopaloglou Can you distribute this to your team

**Comment by dtopaloglou** [comment]
@ddicorpo Are all of these Non-Functional Requirements part of section 3.3?

**Comment by dtopaloglou** [comment]
@SOEN341-W16/coding Hey guys. Please have a look at the document I've already committed in this issue. See if we can add the non-functional requirements in there. I've written a few out, but proper "language" use should be used as mentioned in class today.
