### ISSUE TITLE
Section 4.1 Human Resources

### ISSUE THREAD

**Issue by claudds** [SOEN341-W16/ConUScheduler#26]
This section focuses on outlining the strengths and weaknesses of all of the team members. After outlining every team member's qualities, you should give their role on the team and why they were assigned this role or took this role voluntarily. 

This section was delegated to @SOEN341-W16/coding 
# Description

---

Present here all your team members in terms of their capacities (strengths, knowledge, experience), as well as an evaluation of the time they can consecrate to the project over the semester,  and possible lack of availability during certain periods, which is important information to consider for concrete planning

**Comment by lori-dalkin** [comment]
So elsewhere in the other comments it was suggested that I be assigned this task, but wouldn't it make more sense for everyone to write their own strengths and weaknesses? I can put everything together at the end and edit it.

**Comment by dtopaloglou** [comment]
@lori-dalkin maybe we can create a Google Document and everyone fills in their details and then you can upload the document on Git?

**Comment by lori-dalkin** [comment]
I think that would be the best plan of action. I'll create the document.
