### ISSUE TITLE
Section 8.1 - Prototype

### ISSUE THREAD

**Issue by claudds** [SOEN341-W16/ConUScheduler#44]
I suppose for this section, we need to explain the process we went through and the technologies used to create a prototype and compare it to how we'll be implementing the rest of our code, which should be similar as well!
# Description

<em>Describe any work undertaken in development of a prototype.  A prototype should be developed during this phase both to prove the technologies used are appropriate to the task and to assess the competence of the team to work with the selected technologies.</em>

**Comment by dtopaloglou** [comment]
@SOEN341-W16/coding :smile:
