### ISSUE TITLE
Course data acquisition 

### ISSUE THREAD

**Issue by dtopaloglou** [SOEN341-W16/ConUScheduler#6]
The object is to collect all the necessary course data such as credits, descriptions, prerequisites/co-requisites, technical electives, general education electives and basic science courses.
- Data must be in excel sheet
- Relevant column names.
- Column names should be lower-case and separated by an underscore for word separation 

Example:

| course_name | course_description | credits |
| --- | --- | --- |
| COMP 248 | Object Oriented Programming I | 3.5 |
| COMP 249 | Object Oriented Programming II | 3.5 |

For now, simply collect all data pertaining to Software Engineering. Asking the professor if we need to collect all of the data for all programs (doubtful). Also, you might need more than just those 3 columns shown in the example above.

Reference: http://www.concordia.ca/academics/undergraduate/calendar/current/sec71/71-70.html

/cc @BDSchoeler 
/cc @erinb90

**Comment by erinb90** [comment]
I guess we can't have multiple assignees on things. I didn't mean to unassign you, Lori ^_^

**Comment by lori-dalkin** [comment]
No worries. I've been assigned and unassigned this issue multiple times by this point. I'll just re assign it. Maybe we should make multiple sections for this?

**Comment by dtopaloglou** [comment]
@erinb90 Yea, only one person is responsible. It's the assignee's "responsibility" to give out the information to those who are going to collaborate with you :smile:

**Comment by dtopaloglou** [comment]
@lori-dalkin Just keep yourself assigned. The important thing is doing commits so that your name comes up. It's important to make commits with the issue number attached to the commit so the teacher can track what's going on.

**Comment by dtopaloglou** [comment]
@lori-dalkin How much have you managed to gather?

**Comment by lori-dalkin** [comment]
All fall and winter info for COMP
Working on SOEN. 

Info still missing
-Credits for general electives (I believe Bryce has this assigned)
-Prereqs for general electives and basic sciences. 
-Fall and winter sections for general electives and basic sciences. 
-Anything to do with summer sections.

**Comment by dtopaloglou** [comment]
@lori-dalkin Perfect. Also, I think General Elective courses were all 3 credits each since I last checked. Anyway, we'll double-check just in case.

**Comment by lori-dalkin** [comment]
I'll work on it more, anyone can feel free to take on part of the task and I'll push what I got on Friday during our meeting. 

I can't tag people on my phone so hopefully other coding members will see this.

**Comment by dtopaloglou** [comment]
@lori-dalkin is this complete?
