### ISSUE TITLE
Deliverable 2 - 2   Introduction to part 2

### ISSUE THREAD

**Issue by ddicorpo** [SOEN341-W16/ConUScheduler#70]
The instructions provided in blue are there to provide you indications describing the expected content of the respective sections. They are all to be deleted and replaced with appropriate content.

The introduction of the document provides an overview of the entire document, briefly introducing what are its goals, and what information is to be found in it.

**Comment by RyanL94** [comment]
#70 it's been pushed but it may be in the wrong place... it's with the gantt chart and sequence diagrams
