### ISSUE TITLE
Deliverable 2 - 3.1	Architecture Diagram

### ISSUE THREAD

**Issue by ddicorpo** [SOEN341-W16/ConUScheduler#71]
A 4+1 Architectural View depicting the high-level structure of the system, accompanied by text describing the rationale of this design, and the reasons for any discrepancies with the one presented in the first deliverable. It is mandatory that the system be divided into at least two subsystems, and that the purpose of each of these subsystems be exposed here.

**Comment by ddicorpo** [comment]
@dtopaloglou @AlineTheAlien This is our part

**Comment by AlineTheAlien** [comment]
Oops @ddicorpo I unassigned you by accident LOL, not sure how to assign 2 or more ppl
