### ISSUE TITLE
Deliverable 2 - 5.   Dynamic Design Scenarios (sequence diagram)

### ISSUE THREAD

**Issue by ddicorpo** [SOEN341-W16/ConUScheduler#75]
Give a full dynamic design of two substantial (i.e., having at least 3 system operations) use cases including system sequence diagrams operational contracts, and sequence diagrams. Units and subsystems depicted here must be compatible with the descriptions provided in section 2 and 3.

**Comment by ddicorpo** [comment]
@RyanL94 Your part :)

**Comment by claudds** [comment]
@RyanL94 we'll split the use cases in 2? I'll take the last 6, you take the first? :)
