### ISSUE TITLE
Deliverable 2- 7.  Rapid Prototyping and Risk

### ISSUE THREAD

**Issue by ddicorpo** [SOEN341-W16/ConUScheduler#77]
Rapid Prototyping Report: List and comment prototypes of modules, drivers or stubs implemented.  Give the effect of this work on the design decisions made in the above.  Give the effect on the risks identified in the first report, the effect on the estimate, and on any scope changes.

List all work related to prototyping involving:
Classes or modules
Testing code including drivers and stubs implemented
Technologies used including but not limited to any versioning system, groupware, frameworks if used and databases.

**Comment by ddicorpo** [comment]
@BDSchoeler Teamwork!!! :)

**Comment by dtopaloglou** [comment]
@BDSchoeler I'll take a look at this soon.

**Comment by Ideawin** [comment]
@dtopaloglou Just making sure you knew and we are not doing the same thing, I continue on the file that you have pushed, right? If there's anything let me know.
