### ISSUE TITLE
Super-user

### ISSUE THREAD

**Issue by dtopaloglou** [SOEN341-W16/ConUScheduler#80]
A super-user has the same privileges as a regular user, with the exception of being able to add new users (including modification of users) and modify/delete courses.

**Comment by Malclir** [comment]
@dtopaloglou was the super user created? I don't see it in the database.

**Comment by dtopaloglou** [comment]
@MarcLeclair The super user is simply a boolean in the database called: "**isAdmin**". It's located in the users table.
