### ISSUE TITLE
Schedule Planner page layout and forms

### ISSUE THREAD

**Issue by dtopaloglou** [SOEN341-W16/ConUScheduler#85]
How do we want the scheduling page to look like? Is it accessed via a tab or somewhere else? What will this page require for the user to create a proper schedule?

We need to include preferences also as well as a save button.

**Comment by dtopaloglou** [comment]
@erinb90 @Ideawin I'll leave this for you guys to do, if you have questions, let me know.

**Comment by Malclir** [comment]
@dtopaloglou  wasn't this done already in the scheduler planner tab?

**Comment by erinb90** [comment]
@MarcLeclair the Schedule Planner page was created but has almost nothing on it. We need to figure out how the layout is going to be.

**Comment by dtopaloglou** [comment]
@MarcLeclair like @erinb90  said, I created an empty canvas in the Schedule Planner tab. In there should be where the user creates/edits his schedule as we all saving a schedule.
